version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:7328@db:5432/consultorio_db
  
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7328
      POSTGRES_DB: consultorio_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: